### ISSUE TITLE
Release in Maven Central Repository

### ISSUE THREAD

**Issue by keklabs** [pgelinas/jackson-javax-json#1]
I could not find any release of this module in Maven Central Repository to make dependency on it from my testing project. I want to replace standard JSR 353 provider with Jackson implementation in my testing project.
Please publish some stable version.
Thank you very much

**Comment by maherbel** [comment]
Hey did you manage to get your hands on a stable version ??

**Comment by pgelinas** [comment]
I never got around to make the request for maven central access. Release on maven central should happen during the day.

**Comment by maherbel** [comment]
Great! Thanks again mate.
Le 22 janv. 2015 14:25, "Pascal Gélinas" notifications@github.com a écrit
:

**Comment by pgelinas** [comment]
Project has been released in maven central, should be available in a couple of hours. I've also added the artifact in the release section on github. Enjoy!
