### ISSUE TITLE
JsonObject.getXXX .... NullPointerException - if the specified name doesn't have any mapping

### ISSUE THREAD

**Issue by helmut-at-work** [pgelinas/jackson-javax-json#6]
As far as I understand a call to: 
JsonObject#int getInt(String name,  int defaultValue)
http://docs.oracle.com/javaee/7/api/javax/json/JsonObject.html#getInt-java.lang.String-int-
should not throw a NullPointerException.
Same for all getXXX with default Parameter.

**Comment by michaelbannister** [comment]
I agree this looks like an oversight in this implementation. I'm going to raise a pull request.
