### ISSUE TITLE
JacksonValueUtils._tokenToValueType not including JsonToken.VALUE_STRING

### ISSUE THREAD

**Issue by Pennix** [pgelinas/jackson-javax-json#9]
when used together with jackson-datatype-jsr353 and spring RestTemplate

`

		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(APPLICATION_JSON_UTF8);
		JsonObjectBuilder params = Json.createObjectBuilder();
		params.add("ClientID", clientId);
		params.add("UserName", username);
		params.add("PassWord", password);
		JsonObject json = restTemplate.postForObject(url, new HttpEntity<JsonObject>(params.build(), headers), JsonObject.class);
`

NullPointerException thrown

JacksonValueUtils. _tokenToValueType 
`

    static {
        _tokenToValueType = new EnumMap<JsonToken, ValueType>(JsonToken.class);
        _tokenToValueType.put(JsonToken.START_ARRAY, ValueType.ARRAY);
        _tokenToValueType.put(JsonToken.START_OBJECT, ValueType.OBJECT);
        _tokenToValueType.put(JsonToken.VALUE_FALSE, ValueType.FALSE);
        _tokenToValueType.put(JsonToken.VALUE_TRUE, ValueType.TRUE);
        _tokenToValueType.put(JsonToken.VALUE_NULL, ValueType.NULL);
        _tokenToValueType.put(JsonToken.VALUE_NUMBER_FLOAT, ValueType.NUMBER);
        _tokenToValueType.put(JsonToken.VALUE_NUMBER_INT, ValueType.NUMBER);
    }
    
    public static ValueType getValueType(JacksonValue<?> value) {
        return _tokenToValueType.get(value.delegate().asToken());
    }
`

**Comment by Pennix** [comment]
sorry for the mistake, i've seen that this has been fixed at 2013-05-17, but the release from maven version 0.9.0 (which is the only version) still has this fault, would you please deploy a new version? thx

**Comment by pgelinas** [comment]
Should be fixed with 1.0.0 just released. Sorry for the delay.
